### ISSUE TITLE
Please remove my co-author's email address from the text file

### ISSUE THREAD

**Issue by hfxunlp** [chloelee1230/nlp_ranking#1]
Excuse me,
the security department of the institute of my co-author contacts her, for they are worry about including email addresses in plain text files, which can be easily matched and extracted, and raises the risk of exposing to phishing emails.
Could you please help remove the email address [here](https://github.com/chloelee1230/nlp_ranking/blob/773468331a99b5ca57bd787acdb2a14c0f3695ab/data-collection/txt/W19-5417.txt#L72)?
Many thanks for your kind help with the problem of my co-author.

**Comment by chloelee1230** [comment]
Hi, I have removed the email per your request. Please let me know if there's anything else I can help with.

**Comment by hfxunlp** [comment]
@chloelee1230 that's all, many thanks again for your efforts and kind help :)
